# Generated by Django 6.1 on 2026-09-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_unlocked',
            field=models.BooleanField(default=False, help_text='Check to unlock certificate for this student'),
        ),
    ]
